apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service-app
  labels:
    app: db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
      - name: db-service-container
        image: awesomecosmonaut/db-service-app:latest
        ports:
        - containerPort: 8080
