apiVersion: v1
kind: Service
metadata:
  name: session-service-service
spec:
  selector:
    app: session-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
